version: '3'
services:
  app:
    ports:
    - "80"
    build:
      context: web/ 
      dockerfile: Dockerfile


  proxy:
    depends_on:
      - app
    ports:
    - "80:80"
    - "443:443"
    build:
      context: proxy/
      dockerfile: Dockerfile
      args:
        YOURAPP_ENV: "LW4ga29sYQo="
