version: '3'
services:
  app:
    build: ./web
    ports:
    - "80"
    volumes:
    - .:/usr/share/nginx/html/

  proxy:
    build: ./proxy
    depends_on:
      - app
    ports:
    - "80:80"
    - "443:443"


 
